var array = ["Пушок","Барсик","Рыжик"];
// for (i = 0;i < array.length; i++ ){
// 	if (array[i] == "Барсик"){
// 		console.log(`У меня есть ${array[i]} Мурка `);
// 	}
// 	if (array[i] == "Рыжик"){

// 	}
// 	if (array[i] == "Пушок"){
// 		console.log(`У меня есть ${array[i]}`); 
// 	}
// }
array.pop();    //удаляет последний элемент массива
console.log(array);
array.push("Kut", "слон", "яблоко",77,true,["String","String2"]);   //добавляет последний элемент массива
console.log(array);